name: AppImage maker

on:
  push:
  pull_request:

jobs:
  build:
    name: Build with Tumbleweed
    runs-on: ubuntu-latest
    container:
      image: "registry.opensuse.org/home/mia/images/images/mpv-ci:stable-deps"

    steps:
    - name: Install packages
      run: zypper install pkg-config qmake6 qt6-base-dev qt6-l10n-tools libqt6svg6-dev libgl-dev libmpv-dev
        # sudo apt-get update
        # sudo apt-get -y install build-essential qmake6 qt6-base-dev qt6-l10n-tools libqt6svg6-dev libgl-dev libmpv-dev
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: qmake
      run: qmake6 MPCQT_VERSION=GithubAction mpc-qt.pro
    - name: make
      run: make
    - name: make install
      run: make install INSTALL_ROOT=AppDir
    - name: ls -R -l AppDir
      run:  ls -R -l AppDir
    - name: Upload mpc-qt AppDir
      uses: actions/upload-artifact@v4
      with:
        name: AppDir
        path: AppDir

  # build_mpv:
  #   name: Build libmpv
  #   runs-on: ubuntu-latest
  #   container:
  #     image: "registry.opensuse.org/home/mia/images/images/mpv-ci:stable-deps"
  #     # env:
  #     #   CC: "${{ matrix.config.cc }}"
  #     #   CXX: "${{ matrix.config.cxx }}"
  #   steps:
  #   - name: Install dependencies
  #     run: |
  #       sudo apt-get update
  #       zypper install -y ccache g++-mingw-w64 gcc-multilib meson nasm ninja-build pkg-config ${{ matrix.wine }}    
  #   # - name: Install dependencies
  #   #   run: |
  #   #     sudo apt-get update
  #   #     sudo apt-get install -y ccache g++-mingw-w64 gcc-multilib meson nasm ninja-build pkg-config ${{ matrix.wine }}    
  #   - name: Checkout repository
  #     uses: actions/checkout@v4
  #     with:
  #       repository: mpv-player/mpv
  #       ref: v0.39.0      
  #   - name: Configure
  #     run: meson setup build --prefix=/usr/local
  #   - name: Build
  #     run: meson compile -C build
  #   - name: Install
  #     run: install -C build
  #   - name: ls -R -l /usr/local
  #     run:  ls -R -l /usr/local
  #   - name: Upload mpv
  #     uses: actions/upload-artifact@v4
  #     with:
  #       name: mpv
  #       path: /usr/local

  craft:
    name: AppImage
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Install packages
      run: |
        sudo apt-get update
        sudo apt-get -y install libfuse2 libqt6svg6-dev libqt6openglwidgets6 qmake6
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Download mpc-qt AppDir
      uses: actions/download-artifact@v4
      with:
        name: mpv
        path: /usr/local
    - name: ls -R -l /usr/local
      run:  ls -R -l /usr/local
    - name: Add /usr/local to PKG_CONFIG_PATH
      run: echo "PKG_CONFIG_PATH=/usr/local/lib:$PKG_CONFIG_PATH" >> $GITHUB_ENV
    # - name: Download mpc-qt AppDir
    #   uses: actions/download-artifact@v4
    #   with:
    #     name: AppDir
    #     path: AppDir
    # - uses: geekyeggo/delete-artifact@v5
    #   with:
    #       name: AppDir
    - name: Install LinuxDeploy
      uses: miurahr/install-linuxdeploy-action@v1
      with:
        plugins: qt appimage
    - name: ls -R -l
      run:  ls -R -l
    - name: Move from AppDir/usr/local/ AppDir/usr/
      run:  mv AppDir/usr/local/* AppDir/usr/
    - name: Make sure mpc-qt is executable
      run:  sudo chmod +x AppDir/usr/bin/mpc-qt
    - name: Remove AppDir/usr/local
      run:  rmdir AppDir/usr/local
    - name: Build AppImage
      run: EXTRA_QT_PLUGINS="svg;" QMAKE=/usr/bin/qmake6 linuxdeploy-x86_64.AppImage --appdir AppDir --custom-apprun ./AppImage/AppRun --plugin qt --output appimage
    - name: ls -R -l
      run:  ls -R -l
    - name: Rename AppImage
      run:  mv *.AppImage mpc-qt-x86_64.AppImage
    - name: Upload AppImage
      uses: actions/upload-artifact@v4
      with:
        name: "mpc-qt-x86_64.AppImage"
        path: ./mpc-qt-x86_64.AppImage
